### PR TITLE
Refactor of connector's constants

### PR DESCRIPTION
**Pull request by pedrobento988**
Refactor of the Hazelcast, Cassandra and ReThink connector constant’s keywords, so that they do not mention sink/source
Settings traits improved so that they do not need each constant to be declared when they are extended. Instead they only need connector's prefix to be declared.

### CODE REVIEW

**Comment by andrewstevenson** [comment]
@pedrobento988 Can you rebase and fix the merge conflicts?

**Comment by pedrobento988** [comment]
Can you confirm me if the master's tests are working?
I was rebasing our code, but meanwhile I was having some weird test results.
So I run your master's tests and I had the same errors. The test report is attached below:
[test_report.zip](https://github.com/datamountaineer/stream-reactor/files/1057676/test_report.zip)

Can you help me?

**Comment by andrewstevenson** [comment]
@pedrobento988 Fixing master now, we had some regression.

**Comment by andrewstevenson** [comment]
@pedrobento988 tests are fixed. Can you try again?

**Comment by pedrobento988** [comment]
Rebase is complete. PR is updated

**Pull request merged**
