### PR TITLE
fixing the namespaces

### PR DESCRIPTION
**Pull request by stheppi**

### CODE REVIEW

**Comment by stheppi** [comment]
I am not sure about consolidating into one. We use different elastic search dependencies. Jvm jar nightmare better be avoided

**Comment by stheppi** [comment]
Users should get the version they use 2 or 5. Why would they get and try both?

**Comment by Antwnis** [comment]
wget stream-reactor.gz 

^ they get all connectors and just unzip them 

Similarly fast-data-dev docker contains all connectors on the classpath

**Comment by stheppi** [comment]
I disagree with you to handle ES5 and ES2 into the same package. TCP connection libs comes with different versions; putting all jars in the same path for two different versions is a recipe for problems.

**Pull request closed without merging**
