### PR TITLE
JMSSource Default Options

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Added ConnectionFactory default
Add config to provide a default converter
Add byte array connect converter which handles optional to allow straight byte passthrough, set using value.converter.

### CODE REVIEW

**Comment by stheppi** [comment]
Awsome! Thanks!

**Comment by andrewstevenson** [comment]
@michaelandrepearce Can you update the docs aswell on a branch?

**Comment by michaelandrepearce** [comment]
Sure will do, Can you point me to this sorry.

**Comment by andrewstevenson** [comment]
@michaelandrepearce I've created this issue for it on the docs repo. https://github.com/datamountaineer/docs/issues/22

**Pull request merged**
